lobby:
  world: "DeathMatchLobby"
  portal:
    pos1:
      x: 5.0
      y: 47.0
      z: 33.0
    pos2:
      x: -5.0
      y: 46.0
      z: 40.0
  spawn:
    x: 0.5
    y: 61.0
    z: 0.5
base_item_prices:
  BUCKET: 5
  MILK_BUCKET: 10
  WATER_BUCKET: 10
  LAVA_BUCKET: 50
  BOW: 20
  ARROW: 1
  CHAINMAIL_HELMET: 40
  CHAINMAIL_CHESTPLATE: 100
  CHAINMAIL_LEGGINGS: 80
  CHAINMAIL_BOOTS: 20
  IRON_HELMET: 40
  IRON_CHESTPLATE: 120
  IRON_LEGGINGS: 100
  IRON_BOOTS: 40
  DIAMOND_HELMET: 60
  DIAMOND_CHESTPLATE: 160
  DIAMOND_LEGGINGS: 120
  DIAMOND_BOOTS: 60
  IRON_SWORD: 20
  DIAMOND_SWORD: 40
  IRON_AXE: 20
  DIAMOND_AXE: 40
  MELON: 1
  BREAD: 3
  COOKED_BEEF: 5
  FLINT_AND_STEEL: 20
  TNT: 30
  ENDER_PEARL: 15
  POTION: 10
  SPLASH_POTION: 10